# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
name: Teencast

# Short bio or description (displayed in the header)
description: Welcome to... well, just listen for yourself.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "https://cdn.discordapp.com/attachments/745458578319736955/820781337321537576/81ea181bc9bd7445970ae653ac209d0f659d5e41.png"

# Site settings
title: The r/teenagers Teencast
description: "Welcome to... well, just listen for yourself."
subtitle: "Welcome to... well, just listen for yourself"
lang: en-us
author: r/teenagers Mods
url: "https://teencast.github.io" # the base hostname & protocol for your site

permalink: /:year/:title.html

#Timezone
timezone: United States/New York

#Setup for Pages
include: ['_pages']

# Build settings
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


theme: jekyll-theme-minimal
